#! /bin/sh

pgrep bspswallow || bspswallow &

# -- WORKSPACES -- #
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 0 1 2 3 4 5 6 7 8 9


# -- THEME -- #
bspc config border_width         3
bspc config window_gap           8
bspc config top_padding		    30
bspc config bottom_padding	     0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color "#bc96da"
bspc config normal_border_color  "#3b4252"

# -- MOUSE -- #
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^5'
bspc rule -a Emacs state=tiled
bspc rule -a plasmashell state=floating center=false
sxhkd &
picom &

#feh --bg-fill $HOME/.config/bspwm/wall

#setxkbmap -option grp:alt_shift_toggle -layout es,us -variant ,intl &
